py_binary(
    name = "demo01_record_write",
    srcs = ["demo01_record_write.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/python/cyber_py3:record",
        "//cyber/demo_base_proto:student_py"
    ] 
)

py_binary(
    name = "demo02_record_read",
    srcs = ["demo02_record_read.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/python/cyber_py3:record",
        "//cyber/demo_base_proto:student_py"
    ] 

)