py_binary(
    name = "demo01_talker_py",
    srcs = ["demo01_talker_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/demo_base_proto:student_py"
    ] 

)

py_binary(
    name = "demo02_listener_py",
    srcs = ["demo02_listener_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/demo_base_proto:student_py"
    ] 

)

py_binary(
    name = "demo03_server_py",
    srcs = ["demo03_server_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/demo_base_proto:addints_proto_py"
    ] 

)

py_binary(
    name = "demo04_client_py",
    srcs = ["demo04_client_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/demo_base_proto:addints_proto_py"
    ] 

)

py_binary(
    name = "demo05_param_server_py",
    srcs = ["demo05_param_server_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/python/cyber_py3:parameter"
    ] 
)

py_binary(
    name = "demo06_param_client_py",
    srcs = ["demo06_param_client_py.py"],
    deps = [
        "//cyber/python/cyber_py3:cyber",
        "//cyber/python/cyber_py3:parameter"
    ] 
)