cc_binary(
    name = "demo01_record_write",
    srcs = ["demo01_record_write.cc"],
    deps = [
        "//cyber",
        "//cyber/demo_base_proto:student_cc",
    ],
)

cc_binary(
    name = "demo02_record_read",
    srcs = ["demo02_record_read.cc"],
    deps = [
        "//cyber",
        "//cyber/demo_base_proto:student_cc",
    ],
)