cc_binary(
    name = "demo01_time",
    srcs = ["demo01_time.cc"],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo02_duration",
    srcs = ["demo02_duration.cc"],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo03_opt",
    srcs = ["demo03_opt.cc"],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo04_rate",
    srcs = ["demo04_rate.cc"],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo05_timer",
    srcs = ["demo05_timer.cc"],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo06_log",
    srcs = ["demo06_log.cc"],
    deps = ["//cyber"],
)